export BIGIP_USERNAME=bigip
export BIGIP_AUTHENTICATION_TYPE=tba
export BIGIP_AUTHENTICATION_PROVIDER=tmos
export BIGIP_DEBUG_LEVEL='2'

export BIGIP_LOCAL_PROTOCOL=https
export BIGIP_LOCAL_HOST=10.201.2.25
export BIGIP_LOCAL_PORT=8443
export BIGIP_LOCAL_URL_PATH=

export BIGIP_RADIUS_PROTOCOL=https
export BIGIP_RADIUS_HOST=10.201.2.30
export BIGIP_RADIUS_PORT=8443
export BIGIP_RADIUS_URL_PATH=

export COMMANDER_SERVER=efserver
export COMMANDER_SECURE=1
export PLUGIN_NAME=EC-BigIp
# required for old framework: pluginVersion
export PLUGIN_VERSION=3.1.2
export RECREATE_CONFIG=0
export AUTOMATION_TESTS_CONTEXT_RUN=Sanity

