version: '3'
services:
  electricflow:
    image: electricflow/efserver:latest
    ports:
    - "8000:8000"
    - "8443:8443"
    - "443:443"
    - "80:80"
    networks:
    - internal
    container_name: electricflow
    hostname: efserver
    tty: true
networks:
  internal:
    driver: bridge
